project:
  type: website
  output-dir:  docs

website:
  title: "Replicating NIMBY"
  navbar:
    left:
      - href: index.qmd
        text: Home
        
      - Final Report_draft.qmd
      - counting_dispensaries_step1.qmd
      - Label the Dispensaries with GeoCodes_step2.qmd
      - calculate crime and dispensaries per capita_step3.qmd
      - build_the_linear_model_step4

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

